[tool.black]
    line-length = 80

[tool.pytest.ini_options]
    addopts = "-x"
    testpaths = [
        "tests",
    ]
    filterwarnings = "ignore::DeprecationWarning"

[tool.pylint.master]
    disable = '''
        invalid-name,
        missing-module-docstring,
        missing-class-docstring,
        missing-function-docstring,
        broad-except,
        no-member,
        logging-not-lazy,
    '''
